services:
  taskify-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: taskify-API
    ports:
      - "5217:8080"  # Map to the port we've been using
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=TaskifyDb;User Id=sa;Password=Taskify2025!;TrustServerCertificate=true;MultipleActiveResultSets=true;
      - Jwt__SecretKey=MyVerySecretKeyForJWTTokensThatIsAtLeast32CharactersLong!
      - Jwt__Issuer=TaskifyAPI
      - Jwt__Audience=TaskifyClient
    depends_on:
      - sqlserver
    networks:
      - taskify-network
    restart: unless-stopped

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: taskify-database
    user: root
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Taskify2025!
      - MSSQL_PID=Express
      - MSSQL_MEMORY_LIMIT_MB=2048
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - taskify-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G
    healthcheck:
      test: ["CMD-SHELL", "exit 0"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  sqlserver_data:
    driver: local

networks:
  taskify-network:
    driver: bridge
